### ISSUE TITLE
Add restart:always to the docker-compose

### ISSUE THREAD

**Issue by Razikus** [balena-io/open-balena#83]
Hi i would like to make a little feature request here - add the restart:always to the docker-compose specification

Today i restarted my server, and after that i forgot to start openbalena again

Little thing but will make a life easier

**Comment by dfunckt** [comment]
That's something that needs to be handled by your init system -- ie. start the openBalena containers at server startup. Do I miss your point?

**Comment by Razikus** [comment]
https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by maggie0002** [comment]
+1. Docker handles it's own starting and stopping, init system shouldn't be required. Agree that the init system makes sense for the included OpenBalena entry point script, but when flattening docker-compose.yml a restart unless stopped would make sense. These can be added manually, but would suggest they are the default.

**Comment by maggie0002** [comment]
Update over on the Balena forums that has helped me resolve this: https://forums.balena.io/t/automatically-restarting-open-balena-after-reboot/205006/15

**Comment by florisvdk** [comment]
@dfunckt Why would you implement a new init system when docker has one built-in. For those that do not want to use the docker init an flag could be added to not add the `restart-unless-stopped`.

The current way of having to make your own init script is just dumb.

**Comment by maggie0002** [comment]
In addition to a more production ready restart policy, the issue of the `production_mode` flag has been raised too: https://github.com/balena-io/open-balena/issues/111

My `docker-compose.override.yml`now looks like this:

```
services:
  api:
    restart: unless-stopped
    environment:
      PRODUCTION_MODE: "true"

  cert-provider:
    restart: unless-stopped

  db:
    restart: unless-stopped

  haproxy:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  registry:
    restart: unless-stopped

  s3:
    restart: unless-stopped

  vpn:
    restart: unless-stopped
    environment:
      PRODUCTION_MODE: "true"
```

How about including a file like this in the repository? Could be a `docker-compose.prod.yml` file, and then for production use could be started with `docker-compose -f docker-compose.yml -f docker-compose.prod.yml up` as per the official Docker documentation: https://docs.docker.com/compose/extends/#multiple-compose-files

By default, starting would then be in development mode, as it is now, so wouldn't be a breaking change for users. Starting by default in development mode (i.e. no restart) is fairly expected. But would provide a clear production workflow. The documentation could then be updated accordingly.
